FROM structurizr/lite
LABEL maintainer="Zsolt Kovacs <kovacs.zsolt@nexius.hu>" \
      version="1.0"
COPY ./structurizr/workspace.dsl /usr/local/structurizr/workspace.dsl
COPY ./structurizr/workspace.json /usr/local/structurizr/workspace.json
